### ISSUE TITLE
Documentation not fully accessible 

### ISSUE THREAD

**Issue by tamelang** [ist-dresden/composum-pages#12]
Hey guys,

I would love to try your tools, but I cannot access all the pages of the documentation. e.g.
https://ist-software.atlassian.net/wiki/spaces/CMP/pages/46305000/Composum+Client+Libraries

A quick getting started guide would be awesome as well. 

BR

**Comment by stoerr** [comment]
The documentation is mostly on https://www.composum.com/ now, inclusively some getting started pages.
