### ISSUE TITLE
Composum-pages installation problem 

### ISSUE THREAD

**Issue by surkoff-v** [ist-dresden/composum-pages#3]
Hi!. I am trying to install composum-pages. I compiled all projects taken from develop branch
composum
composum-assets
composum-pages
composum-platform
composum-prototype

Installed all jars into runing sling launchpad compiled from current trunk branch. I have all composum services active. 

![image](https://user-images.githubusercontent.com/26813558/31655233-efeab660-b330-11e7-9012-b35b7bd1b35a.png)

How can I see "composum pages" page? Or I have to do something else? It is exist any install instruction? 

Thanks.

**Comment by Treibholz1991** [comment]
Another question: It looks like I need to compile the stuff myself. But I can see a profile which is used to upload the stuff to nexus. I cannot access the nexus, but wouldn't it be much nicer to make the jars available for the crowd directly. We could easily install the cms modules with a specific profile as sub packages or something using maven. 
Anyway, I think you guys are doing a very nice job in driving the open source cms with sling.

**Comment by mahsumdemir** [comment]
Same here.
What I see on your Confluence pages are very beautiful and I would like to try them but I am unable to install them on sling 11.

**Comment by mahsumdemir** [comment]
After some trail and erros I saw the following command works for me:

Download sling 11 from their side. and run it on port 9090.
E.g java -jar sling.jar -p 9090

checkout develop branches of composum, composum-platform and composum-pages repos and then run the following maven installs.

cd composum/sling
mvn -s ../settings.xml clean install -PinstallPackage -PinstallBundle -DskipTests=true

cd ../../composum-platform
// this fails on first run but succeeds on the second run, don't know why
mvn -s ../composum/settings.xml clean install -PinstallPackage -PinstallBundle -DskipTests=true

cd composum-pages
mvn -s .travis.settings.xml clean install -PinstallBundle -PinstallPackage -DskipTests=true

**Comment by stoerr** [comment]
Installation problems require to have a careful look at the logs/error.log in the sling directory for occurring errors. The installation procedure and entry page are mentioned on https://www.composum.com/home/pages/setup.html . The nexus upload was just stuff we needed to upload it into our own repository - not meant for public use.

Besides: for a quick look and some tryout without any installation you are welcome to use it to open an account on the Composum Cloud https://www.composum.com/home/cloud.html !
