### ISSUE TITLE
usability problems

### ISSUE THREAD

**Issue by tiwuti** [ist-dresden/composum-pages#30]
### As a user with author rights
It is not possible to create:

- a site
- a page
- a folder
- a file

### Page Browser
**As user with author rights**

- while trying to create a new site there is _no error message_ after hitting the create button. The site dosen't appear in the page browser.

- while trying to create a folder there is a error message, but it is unable for the user to get any useful information out of that error message - they are like _"Error Error while processing /content/.../.../new_file_928592"_

- while trying to upload a file there is the same error message as by creating a folder - _"Error Error while processing /content/.../assets"_

**Comment by ist-rw** [comment]
bad access rules on the test instance - fixed
