### ISSUE TITLE
Can not see component content when public

### ISSUE THREAD

**Issue by craigvu** [ist-dresden/composum-pages#61]
I try to public a site in composum platform but it can not show component content. When I access url
http://localhost:8080/content/sites/site1/home/product.html
It shows 
[https://i.stack.imgur.com/Useno.png](url)

When I access the url: http://localhost:8080/public/sites/site1/home/product.html
 It shows error 404 page not found like this
https://i.stack.imgur.com/xH77N.png
I saw in the error.log
It display
GET /content/sites/mysite/home/test.html HTTP/1.1] com.composum.sling.cpnl.ClientlibTag No clientlib found for path 'null' / category 'composum.pages.components.view' 
After debug , I think I can not see any  content because I run on anonymous mode.
Can someone help me how can I see the content If I see the page by anonymous user.
Please help me.
Thank you

**Comment by stoerr** [comment]
This sounds like a related problem that was discussed in https://github.com/ist-dresden/composum-nodes/issues/221 , and was probably answered in comment https://github.com/ist-dresden/composum-nodes/issues/221#issuecomment-768231135 . So I'd like to close this issue.
